name: Docker Image CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'vlab' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ustc-vlab/filestash

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Extract metadata
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      if: github.ref == 'refs/heads/vlab'
      id: meta
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile.multistage --tag ${{ steps.meta.outputs.tags }}
    - name: Login to ghcr
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      if: github.ref == 'refs/heads/vlab'
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      if: github.ref == 'refs/heads/vlab'
      run: docker push ${{ steps.meta.outputs.tags }}
